name: Deployment - Reusable Workflow

on:
    workflow_dispatch:  
      inputs:
    #     mongodb-uri:
    #       required: true
    #       type: string
        kubectl-version:
            description: Provide the required Kubectl version
            default: v1.30.3
            required: false
            type: string
    #     k8s-manifest-dir:
    #         description: Directory containing Kubernetes manifests files
    #         default: kubernetes/
    #         required: true
    #         type: string 
    #     environment:
    #         description: Provide the Deployment Environment
    #         default: dev
    #         required: true
    #         type: string
    #   outputs:
    #     application-url:
    #        value: ${{ jobs.reuse-deploy.outputs.APP_INGRESS_URL  }} 
    #   secrets:
    #     k8s-kubeconfig:
    #       required: true
    #     mongodb-password:
    #       required: true


jobs:
    reuse-deploy:
        # environment: 
        #     name: ${{ inputs.environment }}
        #     url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
        # outputs:
        #     APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Install kubectl CLI
              uses: azure/setup-kubectl@v3
              with:
                version: '${{ inputs.kubectl-version }}'

            - name: Set Kubeconfig file
              uses: azure/k8s-set-context@v3
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.K8S_KUBECONFIG }}

            - name: Fetch Kubernetes Cluster Details
              run: |
                kubectl version
                echo ---------------------------------------------------
                kubectl config view
                kubectl config get-contexts
                # kubectl get nodes
            